import {
  AcademicProfile,
  ApplicationStage,
  CohortHeatmapDatum,
  Document,
  ExamApplication,
  KpiMetric,
  QuestionBankItem,
  StudentMaster,
  SubjectHierarchy,
  TopicStatus,
  User,
  UserRole,
} from '@coaching-ops/types';
import { Gender, StudentStatus, DocumentType, VerificationStatus } from '@coaching-ops/types';

const now = new Date().toISOString();

export const demoUsers: Record<'admin' | 'faculty' | 'operations', User> = {
  admin: {
    id: 'user-admin-1',
    createdAt: now,
    updatedAt: now,
    email: 'admin@coachingops.dev',
    firstName: 'Aarav',
    lastName: 'Mehta',
    role: UserRole.ADMIN,
    isActive: true,
  },
  faculty: {
    id: 'user-faculty-1',
    createdAt: now,
    updatedAt: now,
    email: 'faculty@coachingops.dev',
    firstName: 'Nisha',
    lastName: 'Iyer',
    role: UserRole.FACULTY,
    isActive: true,
  },
  operations: {
    id: 'user-ops-1',
    createdAt: now,
    updatedAt: now,
    email: 'ops@coachingops.dev',
    firstName: 'Rohan',
    lastName: 'Kapoor',
    role: UserRole.OPERATIONS,
    isActive: true,
  },
};

export const demoAcademicProfiles: Record<string, AcademicProfile> = {
  'student-1': {
    previousSchool: 'Central Academy',
    board: 'CBSE',
    lastScorePercentage: 92,
    targetExam: 'JEE Advanced',
  },
  'student-2': {
    previousSchool: 'Springfield Public',
    board: 'ICSE',
    lastScorePercentage: 88,
    targetExam: 'NEET',
  },
  'student-3': {
    previousSchool: 'Vidya Mandir',
    board: 'State Board',
    lastScorePercentage: 84,
    targetExam: 'JEE Main',
  },
};

export const demoStudents: StudentMaster[] = [
  {
    id: 'student-1',
    createdAt: now,
    updatedAt: now,
    rollNumber: 'IIT-2401',
    firstName: 'Ishita',
    lastName: 'Sharma',
    dateOfBirth: '2008-03-14',
    gender: Gender.FEMALE,
    phone: '9876543210',
    email: 'ishita.sharma@example.com',
    currentBatchId: 'batch-alpha',
    enrollmentDate: new Date('2025-06-10'),
    status: StudentStatus.ACTIVE,
    parentDetails: {
      fatherName: 'Rajesh Sharma',
      motherName: 'Anita Sharma',
      primaryContact: '9876543210',
      email: 'rajesh.sharma@example.com',
    },
  },
  {
    id: 'student-2',
    createdAt: now,
    updatedAt: now,
    rollNumber: 'IIT-2402',
    firstName: 'Vivaan',
    lastName: 'Patel',
    dateOfBirth: '2007-11-09',
    gender: Gender.MALE,
    phone: '9123456780',
    email: 'vivaan.patel@example.com',
    currentBatchId: 'batch-beta',
    enrollmentDate: new Date('2025-06-15'),
    status: StudentStatus.ACTIVE,
    parentDetails: {
      fatherName: 'Mitesh Patel',
      motherName: 'Ritu Patel',
      primaryContact: '9123456780',
    },
  },
  {
    id: 'student-3',
    createdAt: now,
    updatedAt: now,
    rollNumber: 'IIT-2403',
    firstName: 'Kabir',
    lastName: 'Nair',
    dateOfBirth: '2008-01-23',
    gender: Gender.MALE,
    phone: '9988776655',
    email: 'kabir.nair@example.com',
    currentBatchId: 'batch-alpha',
    enrollmentDate: new Date('2025-07-01'),
    status: StudentStatus.PROSPECT,
    parentDetails: {
      fatherName: 'Arun Nair',
      motherName: 'Deepa Nair',
      primaryContact: '9988776655',
    },
  },
];

export const demoDocuments: Record<string, Document[]> = {
  'student-1': [
    {
      id: 'doc-1',
      createdAt: now,
      updatedAt: now,
      studentId: 'student-1',
      documentType: DocumentType.ID_PROOF,
      fileUrl: '/docs/ishita-aadhar.pdf',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedBy: 'Rohan Kapoor',
    },
    {
      id: 'doc-2',
      createdAt: now,
      updatedAt: now,
      studentId: 'student-1',
      documentType: DocumentType.PHOTO,
      fileUrl: '/docs/ishita-photo.jpg',
      verificationStatus: VerificationStatus.PENDING,
    },
  ],
  'student-2': [
    {
      id: 'doc-3',
      createdAt: now,
      updatedAt: now,
      studentId: 'student-2',
      documentType: DocumentType.PREVIOUS_MARKSHEET,
      fileUrl: '/docs/vivaan-marksheet.pdf',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedBy: 'Rohan Kapoor',
    },
  ],
  'student-3': [],
};

export const syllabusHierarchy: SubjectHierarchy[] = [
  {
    id: 'subject-1',
    createdAt: now,
    updatedAt: now,
    courseId: 'course-1',
    name: 'Physics',
    code: 'PHY',
    chapters: [
      {
        id: 'chapter-1',
        createdAt: now,
        updatedAt: now,
        subjectId: 'subject-1',
        name: 'Mechanics',
        sequenceNumber: 1,
        topics: [
          {
            id: 'topic-1',
            createdAt: now,
            updatedAt: now,
            chapterId: 'chapter-1',
            name: 'Vectors',
            sequenceNumber: 1,
            difficultyLevel: 'EASY',
            estimatedHours: 2,
            progress: {
              id: 'progress-1',
              createdAt: now,
              updatedAt: now,
              topicId: 'topic-1',
              batchId: 'batch-alpha',
              facultyId: 'user-faculty-1',
              status: TopicStatus.COMPLETED,
            },
          },
          {
            id: 'topic-2',
            createdAt: now,
            updatedAt: now,
            chapterId: 'chapter-1',
            name: 'Newton Laws',
            sequenceNumber: 2,
            difficultyLevel: 'MEDIUM',
            estimatedHours: 3,
            progress: {
              id: 'progress-2',
              createdAt: now,
              updatedAt: now,
              topicId: 'topic-2',
              batchId: 'batch-alpha',
              facultyId: 'user-faculty-1',
              status: TopicStatus.IN_PROGRESS,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'subject-2',
    createdAt: now,
    updatedAt: now,
    courseId: 'course-1',
    name: 'Chemistry',
    code: 'CHEM',
    chapters: [
      {
        id: 'chapter-2',
        createdAt: now,
        updatedAt: now,
        subjectId: 'subject-2',
        name: 'Atomic Structure',
        sequenceNumber: 1,
        topics: [
          {
            id: 'topic-3',
            createdAt: now,
            updatedAt: now,
            chapterId: 'chapter-2',
            name: 'Quantum Numbers',
            sequenceNumber: 1,
            difficultyLevel: 'HARD',
            estimatedHours: 2,
            progress: {
              id: 'progress-3',
              createdAt: now,
              updatedAt: now,
              topicId: 'topic-3',
              batchId: 'batch-beta',
              facultyId: 'user-faculty-1',
              status: TopicStatus.PENDING,
            },
          },
        ],
      },
    ],
  },
];

export const demoApplications: ExamApplication[] = [
  {
    id: 'application-1',
    createdAt: now,
    updatedAt: now,
    studentId: 'student-1',
    student: {
      id: 'student-1',
      firstName: 'Ishita',
      lastName: 'Sharma',
      email: 'ishita.sharma@example.com',
      status: StudentStatus.ACTIVE,
    },
    examName: 'JEE Advanced 2026',
    stage: ApplicationStage.READY_FOR_SUBMISSION,
    submittedAt: now,
    documents: demoDocuments['student-1'],
    checklist: [
      {
        id: 'check-1',
        createdAt: now,
        updatedAt: now,
        documentId: 'doc-1',
        label: 'Aadhaar verification',
        status: 'VERIFIED',
        reviewer: 'Rohan Kapoor',
      },
      {
        id: 'check-2',
        createdAt: now,
        updatedAt: now,
        documentId: 'doc-2',
        label: 'Passport photo review',
        status: 'PENDING',
      },
    ],
    paymentSummary: {
      totalFee: 5200,
      paidAmount: 4000,
      dueAmount: 1200,
      dueDate: '2026-04-30',
      status: 'PENDING',
    },
    timeline: [
      {
        id: 'timeline-1',
        createdAt: now,
        updatedAt: now,
        stage: ApplicationStage.DRAFT,
        title: 'Application draft created',
        description: 'Initial intake form synced from student master.',
        occurredAt: '2026-04-03',
        actorName: 'Admissions Bot',
      },
      {
        id: 'timeline-2',
        createdAt: now,
        updatedAt: now,
        stage: ApplicationStage.DOCUMENTS_PENDING,
        title: 'Documents requested',
        description: 'Operations team requested photo retake.',
        occurredAt: '2026-04-10',
        actorName: 'Rohan Kapoor',
      },
      {
        id: 'timeline-3',
        createdAt: now,
        updatedAt: now,
        stage: ApplicationStage.READY_FOR_SUBMISSION,
        title: 'Application pack ready',
        description: 'Checklist nearly complete and queued for final review.',
        occurredAt: '2026-04-19',
        actorName: 'Operations Desk',
      },
    ],
  },
  {
    id: 'application-2',
    createdAt: now,
    updatedAt: now,
    studentId: 'student-2',
    student: {
      id: 'student-2',
      firstName: 'Vivaan',
      lastName: 'Patel',
      email: 'vivaan.patel@example.com',
      status: StudentStatus.ACTIVE,
    },
    examName: 'NEET 2026',
    stage: ApplicationStage.DOCUMENTS_PENDING,
    documents: demoDocuments['student-2'],
    checklist: [
      {
        id: 'check-3',
        createdAt: now,
        updatedAt: now,
        documentId: 'doc-3',
        label: 'Marksheets review',
        status: 'VERIFIED',
        reviewer: 'Rohan Kapoor',
      },
    ],
    paymentSummary: {
      totalFee: 4600,
      paidAmount: 4600,
      dueAmount: 0,
      status: 'CLEAR',
    },
    timeline: [
      {
        id: 'timeline-4',
        createdAt: now,
        updatedAt: now,
        stage: ApplicationStage.DRAFT,
        title: 'Imported from CRM',
        description: 'Student application pulled from counseling pipeline.',
        occurredAt: '2026-04-08',
        actorName: 'Admissions Bot',
      },
    ],
  },
  {
    id: 'application-3',
    createdAt: now,
    updatedAt: now,
    studentId: 'student-3',
    student: {
      id: 'student-3',
      firstName: 'Kabir',
      lastName: 'Nair',
      email: 'kabir.nair@example.com',
      status: StudentStatus.PROSPECT,
    },
    examName: 'JEE Main 2026',
    stage: ApplicationStage.DRAFT,
    documents: demoDocuments['student-3'],
    checklist: [],
    paymentSummary: {
      totalFee: 3500,
      paidAmount: 0,
      dueAmount: 3500,
      dueDate: '2026-05-02',
      status: 'PENDING',
    },
    timeline: [],
  },
];

export const questionBank: QuestionBankItem[] = [
  {
    id: 'question-1',
    createdAt: now,
    updatedAt: now,
    subject: 'Physics',
    chapter: 'Mechanics',
    difficulty: 'MEDIUM',
    prompt: 'A body starts from rest under constant acceleration. Find displacement after 4 seconds.',
    tags: ['kinematics', 'numerical'],
  },
  {
    id: 'question-2',
    createdAt: now,
    updatedAt: now,
    subject: 'Chemistry',
    chapter: 'Atomic Structure',
    difficulty: 'HARD',
    prompt: 'Explain the significance of azimuthal quantum number with examples.',
    tags: ['theory', 'quantum'],
  },
  {
    id: 'question-3',
    createdAt: now,
    updatedAt: now,
    subject: 'Mathematics',
    chapter: 'Limits',
    difficulty: 'EASY',
    prompt: 'Evaluate lim x->0 sin x / x.',
    tags: ['limits', 'conceptual'],
  },
];

export const leadershipKpis: KpiMetric[] = [
  { id: 'kpi-1', label: 'Total Enrollment', value: '1,248', delta: '+6.3% QoQ' },
  { id: 'kpi-2', label: 'Average Test Score', value: '78.4%', delta: '+3.1 pts' },
  { id: 'kpi-3', label: 'Application Completion Rate', value: '86%', delta: '+11%' },
  { id: 'kpi-4', label: 'Faculty Syllabus Closure', value: '72%', delta: '+8%' },
];

export const leadershipHeatmap: CohortHeatmapDatum[] = [
  { cohort: 'XI Alpha', subject: 'Physics', readinessScore: 82 },
  { cohort: 'XI Alpha', subject: 'Chemistry', readinessScore: 74 },
  { cohort: 'XI Alpha', subject: 'Mathematics', readinessScore: 88 },
  { cohort: 'XII Beta', subject: 'Physics', readinessScore: 69 },
  { cohort: 'XII Beta', subject: 'Chemistry', readinessScore: 77 },
  { cohort: 'XII Beta', subject: 'Mathematics', readinessScore: 72 },
];
